project:
  type: book

book:
  title: "Death, Destruction, and Data"
  subtitle: "An Intro to Using Data to Study International Conflict"
  author: "Miles D. Williams"
  date: "3/20/2026"
  chapters:
    - index.qmd
    - 01_what_is_war.qmd
    - 02_the_data.qmd
    - 03_is_war_disappearing.qmd
    - 04_is_war_less_deadly.qmd
    - 05_dyads.qmd
    - 06_power.qmd
    - 07_democracy.qmd
    - 08_trade.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

